version: "3.5"
services:
  db:
    image: postgres:10.5
#    volumes:
#      - storage_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=finces
      - POSTGRES_PASSWORD=finces
      - POSTGRES_DB=finces
      - PGPORT=5432
    ports:
      - "5432:5432"

volumes:
  storage_db:
  storage_es:
  storage_fs: